### ISSUE TITLE
Self return type is breaking change

### ISSUE THREAD

**Issue by Stratadox** [solariumphp/solarium#1097]
**Solarium version(s) affected**: 6.2.3
**Solr version**: -
**Solr mode**: standalone / cloud

**Description**
The : self return type hint is a breaking change

**How to reproduce**
- Use ^6.2, extend Query / add custom setQuery method with : QueryInterface return type
- Run composer update
- Encounter PHP fatal error

**Possible Solution**
Revert setQuery return type to QueryInterface, possibly schedule return type upgrade for 7.0.

**Additional context**
PHP Fatal error:  Declaration of Custom\OwnQuery::setQuery(string $query, ?array $bind = null): Solarium\Component\QueryInterface must be compatible with Solarium\QueryType\Select\Query\Query::setQuery(string $query, ?array $bind = null): Solarium\QueryType\Select\Query\Query

**Comment by thomascorthals** [comment]
@Stratadox Which PHP version are you using?

**Comment by Stratadox** [comment]
8.1 currently

**Comment by thomascorthals** [comment]
Does the error disappear if you change the return type to `: self` on your custom method?

**Comment by Stratadox** [comment]
It does, although I had to change it inside the vendor directory, as the custom query is defined by another library

**Comment by thomascorthals** [comment]
From a GitHub search for [`(Solarium AND QueryInterface AND extends AND "function setQuery") language:PHP NOT org:solariumphp NOT is:fork`](https://github.com/search?q=%28Solarium+AND+QueryInterface+AND+extends+AND+%22function+setQuery%22%29+language%3APHP+NOT+org%3Asolariumphp+NOT+is%3Afork&type=code&ref=advsearch), it would appear that [integratedfordevelopers/integrated](https://github.com/integratedfordevelopers/integrated) is the only project affected by this. Is that the one you're using?

**Comment by Stratadox** [comment]
Ha, yes it is... Nice query :smile: If it's the only one, I suppose I could open an issue or PR there. 
My build suddenly broke, I tracked it down to this library: it's the one that changed its interface in a minor version increase. 

Wouldn't it be better to change the return type back to QueryInterface tho? Returning **self** refers to the query class, which means it's a narrowing of the declaration as defined on the interface - which also returns **self**, but in it's context, resolves to QueryInterface.

For cases like this, where **self** would narrow the type, there's also **static** as return type (since 8.0) which would probably be the ideal. I'd propose using QueryInterface for now, and moving to **static** in the next major.

**Comment by thomascorthals** [comment]
If they could bump their minimal PHP version to 7.4 (which is also already EOL) and change the return type to `self`, that would fix it for now. But then it'll break again if we change that to `static` because you can't use `self` if the parent is `static`.

#1087 changed the return type to `self` on dozens of methods. But I don't think this will be a problem for others. I don't see a use case for extending them in your own code.

**Comment by thomascorthals** [comment]
I've opened a PR to change it back to `QueryInterface` and added tests that will throw that fatal error if we change the return type to `self` or `static` at a later point.

Not saying we should never do that because of those tests throwing an error. They'll serve as a warning that it's a BC breaking change and make us think twice about versions and documenting it better.

**Comment by thomascorthals** [comment]
@Stratadox The fix has been released in [Solarium 6.3.3](https://github.com/solariumphp/solarium/releases/tag/6.3.3) so you should be good to go.
