### ISSUE TITLE
Q: which versions of SOLR are supported?

### ISSUE THREAD

**Issue by mroeling** [solariumphp/solarium#1111]
I might have missed this information in the docs, but still would like to know if possible. Thanks in advance!

**Comment by thomascorthals** [comment]
There is no hard limit on the Solr version you can talk to. Solarium never checks the Solr version when executing a query (or API call). As long as the request is understood by Solr and the response is understood by our parser, it'll be handled just fine.

However, we can't guarantee that there are no breaking changes for Solr 6 or older because we no longer actively test against them during development. Integration tests are run daily and on every pull request against the latest Solr 7.7, 8.11 and 9.4. Whenever Solr releases x.y+1, we bump the minor version we test against and check compatibility. New patch versions (the z in version x.y.z) are picked up automatically by the test workflow.

**Comment by mroeling** [comment]
Roger. Thanks for the fast response!
