### ISSUE TITLE
$query->setParam($name, $value) with same name doesn't reflect to solr request

### ISSUE THREAD

**Issue by trepmag** [solariumphp/solarium#1128]
**Solarium version(s) affected**: 6.3.5
**Solr version**: 9.6.1 (but should affect any)
**Solr mode**: standalone

**Description**

You might need to specify multiple values for the same parameter name such as the following which is taken into account with solr directly:
- f.myField.facet.prefix=someprefix
- f.myField.facet.prefix=anotherprefix

**How to reproduce**
Using solarium you might set the above parameters as follow:
```php
$query->addParam('f.myField.facet.prefix', 'someprefix');
$query->addParam('f.myField.facet.prefix', 'anotherprefix');
```

Then only the latest second line will be reflected to the solr backend!...

**Possible Solution**
Maybe threatening the 2nd argument of `addParam` when it's an array as multiple affectation which would, as far I could observe, would need multiple adaptations in request and query classes.

**Comment by thomascorthals** [comment]
That method name is indeed misleading as it behaves like you'd expect from `setParam()`. But it's intended for internal use and as you noted would take some doing to change.

If there can be multiple values for the same parameter, Solarium lets you set those with intuitive method calls. In the case of facet prefixes, this isn't possible because Solr ignores all but the first prefix anyway as far as I can tell. Therefore, you can only set a single field prefix like this:

```php
$facetset = $query->getFacetSet();
$facetset->createFacetField('myField')->setField('myField')->setPrefix('someprefix');
```

If you do have a working example with multiple prefixes (preferably against the `techproducts` example core so we can reproduce it), I'll be happy to reevaluate this on Solarium's end. This should work to create a request with multiple prefixes:

```php
$query->addParam('f.myField.facet.prefix', ['someprefix', 'anotherprefix']);
```

**Comment by trepmag** [comment]
> In the case of facet prefixes, this isn't possible because Solr ignores all but the first prefix anyway as far as I can tell

Indeed, sorry I tried it on a small set and could notice exactly that despite the response header is showing multiple values for the same `"f.genre_s.facet.prefix":["fa","sc"]` parameter; e.g.:
```json
{
  "responseHeader":{
    "status":0,
    "QTime":2,
    "params":{
      "q":"*:*",
      "facet.field":"genre_s",
      "indent":"true",
      "q.op":"OR",
      "rows":"10",
      "f.genre_s.facet.prefix":["fa","sc"],
      "facet":"true",
      "useParams":"",
      "_":"1721746379435"
    }
  }
```

Thank you answering this; then only option left here is closing the comment...

**Comment by trepmag** [comment]
Could find that the willing to use multiple prefixes can be obtained using `facet.matches`; e.g.: `f.genre_s.facet.matches=^(fa|sc).*$` which would return:
```json
{

"facet_fields":{
      "genre_s":["fantasy",11,"scifi",2]
    }

}
```
