### ISSUE TITLE
HOWTO: Partial Update

### ISSUE THREAD

**Issue by puyt** [solariumphp/solarium#159]
This is not really an issue but didn't know where to put it, i've read that the new solarium version supports partial updates like: 

curl 'localhost:8983/solr/update?commit=true' -H 'Content-type:application/json' -d '[{"id":"1","price":{"set":100}}]'

how can i make this work in solarium ?
# 

UPDATE: found it, wasn't really clear without an example but after some searching i found out how it works:

$doc2 = $update->createDocument();
$doc2->setKey('id', 1);

$doc2->addField('price', '100');
$doc2->setFieldModifier('price', 'set');

sorry for the trouble, this issue may be closed.
greetings

**Comment by nisha-kajale** [comment]
Hi,
I am uploading pdf documents using extract and i want to provide update facility. So that i can update name, document itself and category. 
I want rest of the fields to remain intact when i run update query.
Currenltly when i am uploading document using https://github.com/solariumphp/solarium/blob/master/examples/2.7-extract-query.php

This adds n number of fields with the document.
When i try to update using the code below
$target_dir = __DIR__;
    $target_file = $target_dir . "\\". basename($_FILES["fileToUpload"]["name"]);
    if (move_uploaded_file($_FILES["fileToUpload"]["tmp_name"], $target_file)) {
        echo "The file ". basename( $_FILES["fileToUpload"]["name"]). " has been uploaded.";
        //print($target_file); exit;
    
    // if data is posted add it to solr

    // create a client instance
    $client = new Solarium\Client($config);
    $query = $client->createExtract();
    $query->addFieldMapping('content', 'pdf');
    $query->setUprefix('attr_');
    $query->setFile($target_file);
    $query->setCommit(true);
    $query->setOmitHeader(false);
    // get an update query instance
    $update = $client->createUpdate();

    // create a new document for the data
    // please note that any type of validation is missing in this example to keep it simple!
    $doc = $update->createDocument();
    $doc->id = $_POST["id"];
    $doc->category = $_POST["category"];
    $doc->attr_src = "http://localhost/solarium/vendor/solarium/solarium/examples/".$_FILES["fileToUpload"]["name"];
    $query->setDocument($doc);
 
    // add the document and a commit command to the update query
    $update->addDocument($doc, true);
    $update->addCommit();
    $result = $client->extract($update);
    // this executes the query and returns the result
    $result = $client->update($update);

    echo '<b>Update query executed</b><br/>';
    echo 'Query status: ' . $result->getStatus(). '<br/>';
    echo 'Query time: ' . $result->getQueryTime();

Only category and src are getting added with newly uploaded document. And rest all fields which where added when i added document for the first time are getting removed after this update.

Please provide a solution for the same.
