### ISSUE TITLE
Error using spellcheck with query containing same misspelled word multiple times

### ISSUE THREAD

**Issue by sgraham3311** [solariumphp/solarium#184]
I am using solarium version 3.1.1. 

Spellcheck throws an error when the query has an AND or an OR in it.

**Query Used:** (message:(enrgy)) OR (comment:(enrgy)) 
**Query Used:** (message:(enrgy)) AND (comment:(enrgy))

**Errors Recieved:**

Severity: Notice

Message: Undefined index: suggestion

Filename: Component/Spellcheck.php

Line Number: 186

---

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: Component/Spellcheck.php

Line Number: 186

**Comment by thomascorthals** [comment]
This bug is no longer reproducible with "power cort" and "power cort cort" against Solr 7 and 8. The JSON output has been changed in [SOLR-3029](https://issues.apache.org/jira/browse/SOLR-3029) for Solr 5 and #320 updated the response parser to handle the new output.

http://localhost:8983/solr/techproducts/spell?df=text&spellcheck.q=power+cort&spellcheck=true&spellcheck.extendedResults=false&spellcheck.collate=true&spellcheck.collateExtendedResults=false

```json
{
  "responseHeader":{
    "status":0,
    "QTime":5},
  "response":{"numFound":0,"start":0,"docs":[]
  },
  "spellcheck":{
    "suggestions":[
      "cort",{
        "numFound":3,
        "startOffset":6,
        "endOffset":10,
        "suggestion":["corp",
          "cord",
          "card"]}],
    "collations":[
      "collation","power corp",
      "collation","power cord",
      "collation","power card"]}}
```
http://localhost:8983/solr/techproducts/spell?df=text&spellcheck.q=power+cort+cort&spellcheck=true&spellcheck.extendedResults=false&spellcheck.collate=true&spellcheck.collateExtendedResults=false

```json
{
  "responseHeader":{
    "status":0,
    "QTime":78},
  "response":{"numFound":0,"start":0,"docs":[]
  },
  "spellcheck":{
    "suggestions":[
      "cort",{
        "numFound":3,
        "startOffset":6,
        "endOffset":10,
        "suggestion":["corp",
          "cord",
          "card"]},
      "cort",{
        "numFound":3,
        "startOffset":11,
        "endOffset":15,
        "suggestion":["corp",
          "cord",
          "card"]}],
    "collations":[
      "collation","power corp corp",
      "collation","power cord corp",
      "collation","power corp cord",
      "collation","power cord cord",
      "collation","power corp card"]}}
```
