### ISSUE TITLE
Bad Content Type for search handler Solr 5.1

### ISSUE THREAD

**Issue by vmasciotta** [solariumphp/solarium#326]
Using Solr 5.1, requests to the searchHandler returns *Bad Content Type for search handler error 400 * response (sending a GET request).

Actually the only way I found to make it works, was to comment the header options cycle in *library/Solarium/Core/Client/Curl.php* line 173 to 179.

I couldn't investigate more and provide a better, valid fix.

**Comment by GregEisenman** [comment]
Hmm, are you sure it wasn't a POST?

It seems there were some changes to the way posting XML works in 5.1, haven't had a chance to look too deeply.

 * When posting XML or JSON to Solr with curl, there is no need to 
specify the content type.  (http://lucene.472066.n3.nabble.com/ANNOUNCE-Apache-Solr-5-1-0-released-tp4199622p4199637.html)
* http://lucene.472066.n3.nabble.com/Bad-contentType-for-search-handler-text-xml-charset-UTF-8-tp4200314p4200451.html

**Comment by lysias** [comment]
Hi,
we have a similar problem since the update to Solr 5.1.

HttpException in Result.php line 103:
Solr HTTP error: OK (400)
{"error":{"msg":"Bad contentType for search handler :text/xml; charset=utf-8 request={q=*:*&json.nl=flat&omitHeader=true&fl=*,score&start=0&rows=10&wt=json}","code":400}}

It looks like Solarium sets a default header to "text/xml; charset=utf-8", so that the new automatic detection from solr won't work.

Changing line 156 in \Solarium\Core\Client\Adapter\Curl createHandle from "$options['headers']['Content-Type'] = 'text/xml; charset=utf-8';" to an empty string seems to work for us.

**Comment by vmasciotta** [comment]
Yes I'm quite sure,
I tried with Firefox RESTClient too using GET and if I add a custom header (any Content Type), I'll get that error... 

To me looks like Solr doesn't accept Content type anymore on both GET and POST...

**Comment by dagnew** [comment]
Seems like the solution could be to change https://github.com/solariumphp/solarium/blob/master/library/Solarium/Core/Client/Adapter/Curl.php#L159
from 'text/xml' to 'application/x-www-form-urlencoded'.

**Comment by macedigital** [comment]
This thread https://www.mail-archive.com/solr-user@lucene.apache.org/msg108800.html explains it all:

GET request aren't supposed to set any Content-Type because you usually don't send any request body at all. Removing the header solves issue with GET requests. See https://gist.github.com/macedigital/ea540099097f7ec4c2f5 for a workaround (curl-adapter). I haven't tested what happens with POST-requests yet, because that depends on many factors and can be solved by setting the appropriate Content-Type header when doing the update/insert).

**Comment by MLoureiro** [comment]
After burning a  few time, I got to the same solution as @dagnew on my tests it worked as expected.
Is there any idea if it will be merged and then a release?

**Comment by murraytm** [comment]
I need this fix as well. Right now I'm maintaining a separate Curl adapter with the corrected contentType but that's less than ideal.

**Comment by basdenooijer** [comment]
Just created a release that fixes this issue.

**Comment by macedigital** [comment]
Much appreciated! I'll try to give feedback before the end of the week

**Comment by machaka** [comment]
Thanks to @dagnew  solution :dancing_men:
