### ISSUE TITLE
Unable to get local issuer certificate with 3.4.0/3.4.1

### ISSUE THREAD

**Issue by eostis** [solariumphp/solarium#343]
Hi,

In Solarium 3.4.0/3.4.1, curl.php is now delivered without
```php
curl_setopt($handle, CURLOPT_SSL_VERIFYPEER, FALSE);
```
The effect was immediate on my Wordpress hosting environment:  access to my https Solr index stopped with error **unable to get local issuer certificate**

Is there a way for environments where one cannot control the CA certificates authorized to overcome this issue ?
Perhaps by adding an option in the api ?

**Comment by basdenooijer** [comment]
This was not there in previous releases (deliberately), could it be that you upgraded your Curl library? Since a specific version (don't know exactly which one) this setting is true by default.

Currently there is no way to set this to false in Solarium. It could be implemented using an option, similar to the proxy setting already supported by the Curl adapter. 
However, the best solution would be to avoid needing this option as you could question the value of a non-verified SSL connection. For some info see: 
https://www.saotn.org/dont-turn-off-curlopt_ssl_verifypeer-fix-php-configuration/

**Comment by eostis** [comment]
You're right. Thanks.
