### ISSUE TITLE
BC break in 3.5.0

### ISSUE THREAD

**Issue by Seldaek** [solariumphp/solarium#382]
The rename of Plugin to AbstractPlugin is a BC break and not really an improvement as the changelog calls it :/ This breaks semantic versioning principles and it's really not helpful for people depending on this library. See https://github.com/nelmio/NelmioSolariumBundle/issues/55 for example, we rely on solarium ~3.3 which includes 3.5 but 3.5 is not compatible with 3.3 anymore. There is no way for me to fix it in a BC way either because releasing a version requiring 3.5 would be a BC break as well on my end. The best really would be that you revert that rename or at least add a BC layer like put `abstract class Plugin extends AbstractPlugin {}` in Plugin.php and that way old code keeps running. If that was released in 3.5.1 it would solve the issue.

**Comment by tomahoax** [comment]
+1

**Comment by anrizal** [comment]
+1

**Comment by basdenooijer** [comment]
You're right, I should have paid better attention to that. 

Since I've also heard from some people they fixed to issue by switching to the renamed classes, I don't want to revert the change and cause even more issues. I've just created a PR that adds BC layers for this and the other renamed classes, that should support both cases.

I'll merge it once CI tests and some manual tests have been done, and try be more careful in the future.

**Comment by Seldaek** [comment]
Great, thanks, you could also add `@deprecated` to the classes you just added so people using IDEs will see the warning, and can then upgrade more smoothly.

And no worries I realize that keeping full BC isn't easy but when you build things people rely on it's nicer :)

**Comment by basdenooijer** [comment]
I've added the 'deprecated' annotations, merged the changes to master and tagged 3.5.1

Thanks for the feedback!

**Comment by Seldaek** [comment]
Cool thanks for the prompt reaction!
