### ISSUE TITLE
reuse the curl connection handlers

### ISSUE THREAD

**Issue by domnulnopcea** [solariumphp/solarium#397]
Hi,

If we do multiple solr queries (tens of thousands) that means opening and closing thousands of curl connections.

this is bad!

why don't reuse the same curl handle!

do you plan to do this?

thanks

**Comment by basdenooijer** [comment]
Well, most use cases only have one Solr query in an application request, so maybe that's why you are the first one to run into (or to report) this issue.

I agree in some use cases it would be useful to reuse the Curl handle, so this could be made configurable. 

A pull request with this functionality would be very welcome

**Comment by domnulnopcea** [comment]
hm...I can not see a case where you would not want to reuse the curl handlers. I do not see a point where we want this to be configurable. You just end up eating less resources by reusing the handlers...

can I send a patch where this is the default behaviour without any other configuration addons?

thanks

**Comment by basdenooijer** [comment]
That case would be when you never intend to re-use it, for example when you do only one query and continue a long running script that never needs to re-query Solr. If the connection is not closed you would leave a socket open for some time, where in some cases it would be better to close resources as soon as you're done.
Since the library cannot know in advance if you are done with Solr queries, the only safe option is to close the the connection by default. 

I think the scenario you describe (with reuse being better) is actually more common, but the library cannot change behaviour except for a major release. Therefore I suggest a configuration option with a default value 'off'. Maybe in the next major release this option could be changed to 'on' by default.

**Comment by MaxamusOne** [comment]
I have used connection reusing a while ago. Let me come back to you with the solution.
The use case was reindexing a quite big full-text index and sending thousands of update queries to solr.

**Comment by domnulnopcea** [comment]
great! thanks a lot

**Comment by domnulnopcea** [comment]
any news here?

**Comment by thomascorthals** [comment]
> any news here?

@domnulnopcea Solarium 6.0 will deprecate the Curl adapter in favour of a [PSR-18](https://www.php-fig.org/psr/psr-18/) compatible implementation as described in #550. You can follow the implementation progress in PR #754.

**Comment by dmaicher** [comment]
@thomascorthals @domnulnopcea we actually did not deprecate the `Curl` adapter in 5.x and it will still exist in 6.0.

But I would argue that we should not further extend its functionality now that we have PSR-18 support. Re-using an existing connection can probably be easily achieved by using some properly configured PSR-18 client and the now existing `Psr18Adapter`.

**Comment by thomascorthals** [comment]
@domnulnopcea You should be able to keep connections open with the [Symphony HttpClient Component](https://symfony.com/doc/current/components/http_client.html) which implements PSR-18.

I haven't tried it yet. We look forward to your feedback if you find the time to test it.

**Comment by mkalkbrenner** [comment]
@thomascorthals it would be great to have this information added to the documentation and close this issue afterwards.

**Comment by tsterker** [comment]
@mkalkbrenner @thomascorthals @domnulnopcea Take the below with a grain of salt, as I did not confirm that the connections were *actually* reused, but in an initial test, it seemed to result in ~20% performance improvement and got rid of my DNS resolution issues during millions of Solr query/update requests.

So this is how I seemed to [get it working](https://github.com/tsterker/Laravel-Solarium#change-http-adapter) with the  [Symphony PSR-18 HTTP Client](https://symfony.com/doc/current/http_client.html#psr-18-and-psr-17):

```sh
composer require psr/http-client
composer require nyholm/psr7
composer require symfony/http-client
```

```php
use Nyholm\Psr7\Factory\Psr17Factory;
use Solarium\Core\Client\Adapter\Psr18Adapter;
use Symfony\Component\HttpClient\Psr18Client;
use Symfony\Component\EventDispatcher\EventDispatcher;

$config = ['endpoint' => ['default' => /** ... */ ]];
$factory = new Psr17Factory();
$adapter = new Psr18Adapter(new Psr18Client(), $factory, $factory);

$client = new Client($adapter, new EventDispatcher, $config);
```

**Comment by tsterker** [comment]
@wickedOne @mkalkbrenner 

Since the [documentation update was merged](https://github.com/solariumphp/solarium/pull/887#event-4453711521), I think this issue [can be closed](https://github.com/solariumphp/solarium/issues/397#issuecomment-641869220).
