### ISSUE TITLE
Solarium 5.0 (what we didn't achieve with 4.x)

### ISSUE THREAD

**Issue by jsteggink** [solariumphp/solarium#490]
In order to get things going and plan for Solarium 4.0, I'd like to get an idea of what improvements and new features people are looking for.

# Features
- Use the new v2 api
- Query Re-Ranking
- Streaming Expressions
- Admin query types
- Filling feature gaps in the existing QueryTypes

# Improvements
- In #489 we discussed going to PHP 7.
- Splitting up some of the methods to traits in order to make room for SolrCloud. For example the distinction between cores and collections.
- Passing Endpoint objects to methods could be removed. Having a central registration of an Endpoint should be ok.
- Move parameter and requesthandler constants to a separate classes (Params classes)

**Comment by thePanz** [comment]
May I add: "use of PHP Http Plug" library? (http://docs.php-http.org/en/latest/) instead of writing our adapters for cUrl/Guzzle , that library can be used to abstract them (ps: I wrote an API client for mattermost, it is quite easy to use phphttp plug! :) )

**Comment by mkalkbrenner** [comment]
As I already told @basdenooijer, I propose to drop support for all software that reached EOL.
According to http://lucene.apache.org/solr/community.html we should only support Solr 6.4 and 7.x.
But if we take into account that the 6.4 "LTS" didn't receive the critical security issues but 6.6 did, I would suggest that solarium 4 should support Solr > 6.6.x.

According to http://php.net/supported-versions.php PHP 5.6 will be supported till end of 2018. Nevertheless I vote for PHP 7 only.

People who need to run an older PHP version or Solr Server could perfectly stay with an old 3.x solarium release.

**Comment by mkalkbrenner** [comment]
@thePanz I like the idea to get rid of all these specific client implementations and to use an abstraction. Are you able to start such an an PR against the 4.x branch, maybe as WIP?

**Comment by thePanz** [comment]
@mkalkbrenner I can start a first implementation, sure! :)

**Comment by thePanz** [comment]
@mkalkbrenner just a small point, are we moving to PHP 7.1, right?

**Comment by mkalkbrenner** [comment]
@thePanz will PHP 7.1 be required? Or does it work PHP 7.0 as well?

**Comment by thePanz** [comment]
@mkalkbrenner I was asking just to know if I can use PHP 7.1 features or not :)

**Comment by mkalkbrenner** [comment]
@thePanz If it's doable I would prefer an implementation that is compatible to 7.0.

The reason is that I maintain the Solr search backend for Drupal 8 as well. The upcoming 2.x release will switch from solarium 3 to 4. At the moment we count aprox. 7.000 active installations of that Drupal 8 module and PHP 7.0 seems to be the most used PHP version in this scenario.

(Nevertheless it would be interesting to see the difference in the implementation.)

**Comment by mkalkbrenner** [comment]
@jsteggink we already covered some of your ideas with Solarium 4.x:

Features
---------
* Use the new v2 api
* Query Re-Ranking **=> done**
* Streaming Expressions **=> done**
* Admin query types
* Filling feature gaps in the existing QueryTypes  **=> partly done**

Improvements
--------------
* In #489 we discussed going to PHP 7.  **=> done**
* Splitting up some of the methods to traits in order to make room for SolrCloud. For example the distinction between cores and collections.  **=> partly done**
* Passing Endpoint objects to methods could be removed. Having a central registration of an Endpoint should be ok.
* Move parameter and requesthandler constants to a separate classes (Params classes)

I suggest to open separate issues for the remaining tasks and to close this one.

**Comment by thePanz** [comment]
@mkalkbrenner : `splitting up some of the methods to traits in order to make room for SolrCloud`... are we *really* using Traits? On a personal level I'd like to try other solutions first :)

**Comment by timohund** [comment]
Hi together, what do you mean with admin query types? Something like 

* Cores: reload, create, swap ...
* ManagedResources: get, add, delete

???

**Comment by mkalkbrenner** [comment]
@timohund I really welcome such a feature. I already described it here:
https://www.drupal.org/project/search_api_solr/issues/2987487

> Please add a todo that the implementation should be moved to the solarium library

**Comment by timohund** [comment]
Thanks for the links. I think managed resources stuff is pretty straight forward since as all other Queries/Requests types it's core specific (which means the baseUri is scheme://host/path/core), but for the core api the core segment needs to be missing scheme://host/path/admin/cores).

I think this required to have Requests core specific or not and to adapt the Adapters. I would propose the following refactoring:

* Add the propery isCoreSpecific to the Request object and default it to "true"
* Check in the Adapter if it is a coreSpecific Request or not.
* Then get the baseUri as needed. This could be implemented by passing a boolean to "getBaseUri". The better way but api breaking would be to have two methods Endpoint::getBaseUri and Endpoint::getCoreBaseUri and call the needed one. In this case Endpoint::getCoreBaseUri would be the current implementation of Endpoint::getBaseUri and Endpoint::getBaseUri would just return the path without the core segment.

I hope i could describe it that it was possible to follow :-) Maybe we could add another issue for that core admin query. But i think first we should decide how breaking a change could be and i guess it makes more sence to have that then in version 5.

**Comment by mkalkbrenner** [comment]
We need to be careful if we talk about cores. All installations I maintain are running Solr cloud.

**Comment by mkalkbrenner** [comment]
All the features mentioned on top are mow basically done and the master branch is 5.x now!
