### ISSUE TITLE
AddListener not working

### ISSUE THREAD

**Issue by bilougit** [solariumphp/solarium#491]
Hi, I developed a search feature based on solarium and it's fine. The problem however, is that now I needed to edit a field in the `documentclass` on the fly (replace db ID with label). I wanted to use solarium events and I was interested into `Solarium\Plugin\BufferedAdd\Event\Events::ADD_DOCUMENT`.

```php
// get_class($this->client) == 'Solarium\Client'
$this->client->getEventDispatcher()->addListener(
    Events::ADD_DOCUMENT, function ($obj) use ($logger) {
        $logger->critical(Events::ADD_DOCUMENT);
        die('die');
});
```

This doesn't stop (neither does it write a message in my logs files) and works exactly as if I didn't add a listener.

**Comment by bilougit** [comment]
Actually I just realized that there is not any event raised when a new `documentclass` is instantiated (`vendor/solarium/solarium/library/Solarium/QueryType/Select/ResponseParser/ResponseParser.php`) which complicates editing a field value on the fly for me.

I can do it myself in my `documentclass` constructor, but it'd be great if there was an event raised natively here `vendor/solarium/solarium/library/Solarium/QueryType/Select/ResponseParser/ResponseParser.php:85`

Given that
```json
"name": "solarium/solarium",
"version": "3.7.0",
```

**Comment by jsteggink** [comment]
I'm not quite following what you are trying to accomplish. Could you eloborate a bit?
From what I understand is you are trying to edit a document. Is it a custom class or this one "Solarium\QueryType\Update\Query\Document\Document"?

It's not really clear to me why you are mentioning Events:ADD_DOCUMENT, which is an event triggered when adding documents to Solr versus retrieving documents  using ResponseParser.

Let's say we add an event in ResponseParser. What is the reason you need to do this add exactly this point (before or after line 85) and not just alter the data after you retrieve them from the parse method?

**Comment by bilougit** [comment]
Hi @jsteggink , actually I'm using a custom `documentclass`. In this class I have a field called `$contentType` which is filled with an ID. I want to replace that ID by its label which I get from a `MySQL` database.

The problem is that I can't inject anything to that custom `documentclass`, so I can't edit the wanted field on the fly based on the database data. So I have to iterate over all retrieved documents and edit the field afterwards.
If you add an event after the line 85, I'll inject in every `documentclass` my database connection, which will allow me to use the ID, retrieved from `solr`, to get its label from my main database (`MySQL`).

**Comment by jsteggink** [comment]
Hi @bilougit. Since you're using a custom Document class which implements DocumentInterface, you could implement your own Event. But you don't really need an event. You already have a Document class which can do this. For example:

```php

class YourDocument implements \Solarium\QueryType\Select\Result\DocumentInterface
{

protected $id;

public function __construct(array $fields)
{
  $this->fields = $fields;
  $this->id = $this->getIdFromDb($fields);
}

public function getIdFromDb($fields)
{
   // get id from fields and lookup in db and return correct id
}
}
```

**Comment by bilougit** [comment]
Please notice that I don't have access to the object of my database handler within `getIdFromDb`. Your solution would work if only I could pass my database object to it. And to pass that database object, I need to call `getIdFromDb` from outside the document class.

```php
public function getIdFromDb($fields, $db)
{}
```

**Comment by jsteggink** [comment]
You are right about that, there is no way to add it to the constructor. I was thinking of adding a database connection via a service in your document class. So it's already there in the class, instead of passing it.

I feel a bit reluctant to burden all document classes with adding an event, since most users won't need it. Firing an event could impact performance when you have a lot of results. Furthermore, what you are trying to do is not really what events (observer pattern) is meant for. Of course you are absolutely free to add an event in your own class and build your own listener.

However, I think there is a better way. We could add a DocumentProcessor to the Document class and pass it to the constructor. Throught the options you can add a documentprocessorclass and the Document class will let the DocumentProcessor handle the fields. What do you think?

**Comment by basdenooijer** [comment]
Basically you want to combine data from Solr with data from the database. Instead of trying to retrofit/mimic database data into your Solr documents, I would suggest to use some kind of decoration on the Solr documents in another layer so the Solr documents only represent the actual Solr result documents.

I'm assuming it's not possible for your scenario to add the data to Solr at indexing time, but are you really sure about this? Because that would likely be the easiest and most efficient solution.

**Comment by jsteggink** [comment]
A decorator requires to be able to add objects to the constructor, which is not possible currently.

I agree that the way it is setup now, the Document class is meant to be a representation of the document which is actually returned by Solr. Transformation of the document could be done by Solr using this method: https://cwiki.apache.org/confluence/display/solr/Transforming+Result+Documents
Of course this doesn't make it possible to use the database.

Maybe what's missing is a way to map Solr documents to some other document structure. Let's say you index documents and you just store some text for highlighting, it's not meant for anything else. In order to map the result document to something in a database, you'll use the document ID to make the mapping.

**Comment by floriansemm** [comment]
> In order to map the result document to something in a database, you'll use the document ID to make the mapping.

My [SolrBundle](https://github.com/floriansemm/SolrBundle) does this job for you.
