### ISSUE TITLE
Feature Request: Add Deletes to BufferedAdd plugin

### ISSUE THREAD

**Issue by lriggle-strib** [solariumphp/solarium#495]
Ability to add a delete (by id or by query) to the 'BufferedAdd' buffer would be incredibly helpful when trying to reduce the number of commits sent to Solr.

For example, if I have a cron that performs a commit every 5 minutes, all of my adds/updates that have been sent to Solr are included in that. However when I do a delete, that appears to require a commit each time I do a check for new or updated items to buffer, which increases the number of commits performed in general.

**Comment by basdenooijer** [comment]
You should be able to send a delete query from Solarium without a commit, this is quite a common usecase when using Solr autocommit. Simply omit the 'addCommit' call in the update query.

**Comment by thomascorthals** [comment]
@lriggle-strib Adding deletes to `BufferedAdd` turned out to be detrimental to its performance. See #971 for the full discussion.

[Solarium 6.2.3](https://github.com/solariumphp/solarium/releases/tag/6.2.3) was released with a [`BufferedDelete` plugin](https://solarium.readthedocs.io/en/latest/plugins/#buffereddelete-plugin) that handles IDs and queries. If you don't use event listeners, there's also a faster `BufferedDeleteLite` version.

If you do need to process interspersed adds and deletes in a fixed order, you'll have to use both plugins (or their lite versions) and manually flush the buffers when going back and forth between them.
