### ISSUE TITLE
Delete nested documents?

### ISSUE THREAD

**Issue by cdekok** [solariumphp/solarium#577]
In a json request it's possible to delete child documents with the following request:
`curl http://localhost:4003/solr/test/update?commitWithin=3000 -d '
[{id : 1, _childDocuments_ : []}]`

Only solarium uses the xml variant and if you pass an empty _childDocuments_ it will not be added to the xml, actually if you would force it to add a empty <doc></doc> element it would still not work.

Is there any solution for this? or anyway to use json requests in the update handler?

**Comment by mkalkbrenner** [comment]
Can you point me to the corresponding Solr documentation?

**Comment by cdekok** [comment]
Itś not documented only (old) bug reports unfortunately. The workaround is described in various issues this post contains most info: https://medium.com/@sarkaramrit2/multiple-documents-with-same-doc-id-in-index-in-solr-cloud-32c072db2164
For now I just worked around it by not using solarium for updates, for a new version the update handler could be simplified a lot by using json.
Am not sure which solr version added the json handler by default though and what solr version solarium still needs to support.

**Comment by mkalkbrenner** [comment]
We do it in drupal's search_api_solr module which uses solarium:
https://www.drupal.org/project/search_api_solr/issues/3066092

**Comment by thomascorthals** [comment]
I'm afraid you can't do that in XML for anonymous children. The documentation about nesting has been overhauled for Solr 8.7 and now clearly states that [anonymous children are not recommended](https://lucene.apache.org/solr/guide/8_7/indexing-nested-documents.html#indexing-anonymous-children). At the moment, this is the only way documents can be nested with Solarium.

The solution will be using labelled pseudo-fields. Work is underway in #872 to implement this functionality. I'm already preparing an integration test for atomic updates and I'll be able to provide example code as well.

**Comment by thomascorthals** [comment]
Since #872, it is possible to atomically remove all nested child documents from a parent document. This functionality will be available in the next Solarium release.

```php
$doc = $update->createDocument();
$doc->setKey('id', '1');
$doc->setField('_childDocuments_', []);
$doc->setFieldModifier('_childDocuments_', $doc::MODIFIER_SET);
$update->addDocument($doc);
self::$client->update($update);
```

I have noticed this often results in errors when doing it in SolrCloud mode with anonymous children. That problem doesn't arise with labelled children.

```php
$doc = $update->createDocument();
$doc->setKey('id', '1');
$doc->setField('children', []);
$doc->setFieldModifier('children', $doc::MODIFIER_SET);
$update->addDocument($doc);
self::$client->update($update);
```

Other atomic updates on child documents aren't possible with XML requests because of [SOLR-12677](https://issues.apache.org/jira/browse/SOLR-12677). When it gets fixed you should be able to atomically add or remove individual child documents through Solarium as well. I'm watching that issue on their JIRA and will update our integration test when that time comes.
