### ISSUE TITLE
PrefetchIterator Behavior Explanation 

### ISSUE THREAD

**Issue by CBox** [solariumphp/solarium#610]
Hey,

I wonder how the Prefetch plugin works, it will iterate everything and get the results back or while we iterate it sends the request?

The reason why it's make a difference is if I pull 1M records all of them going to be saved in the "documents" variable or only the last fetch? (more data to memory)

What's going on when I do count($prefetch)? It's iterate all the result or just return the numFound?

Also is this plugin can work with ParallelExecution plugin?

Thanks a lot!

**Comment by mkalkbrenner** [comment]
The prefetch plugin uses cursormark and should not fetch all documents. But since the latest release you can also leverage cursormark on standard select queries without using the prefetch plugin.

**Comment by CBox** [comment]
It means that I will be able to process all the 1M records without save them to a variable but it will save the last fetch?

**Comment by CBox** [comment]
Last question is the ParallelExecution can work with the PrefetchIterator plugin?

**Comment by mkalkbrenner** [comment]
I assume yes. But I never tried it.

**Comment by mkalkbrenner** [comment]
I recommend to use the standard select with cursormark. That's newer code ;-)

**Comment by CBox** [comment]
Is there any sample code I can take a look at?
Thank you again :)

**Comment by mkalkbrenner** [comment]
We have an example that uses the combination:
https://github.com/solariumphp/solarium/blob/master/examples/7.6-plugin-prefetchiterator.php

I suggest you simply give it a try. And it would be nice if you report back if it works like expected.

**Comment by CBox** [comment]
Just to make sure, if I'm not using this:
`$query->setCursormark('*');
// cursor functionality requires a sort containing a uniqueKey field as tie breaker on top of your desired sorts for the query
$query->addSort('id', $query::SORT_ASC);`

The Prefetch plugin not adding it? I was sure that it's adding it automatically, I've used the sort but not the setCursormark - it mean it was not active right?

**Comment by CBox** [comment]
I guess I missed it here:
`if (null === $this->cursormark) {
            $this->query->setStart($this->start)->setRows($this->getPrefetch());
        } else {
            $this->query->setCursormark($this->cursormark)->setRows($this->getPrefetch());
        }`

Still if you can please verify :)

**Comment by CBox** [comment]
After adding $query->setCursormark('*'); I didn't not get duplicates but there was a lot of data missing.

Can I use my own pagination instead of Prefetch? I will add and update the setCursormark, is it possible?

Thanks!

**Comment by thomascorthals** [comment]
> You suggest to use the prefetch plugin or standard select?

Whether or not you should use prefetch depends on your use case.

For websites, you probably don't need prefetch. If you use classic pagination where users can jump to any specific page, you don't want cursorMark either. (You could use either in this scenario, but you'll end up storing a lot of results in a session that you might not ever need.) Solr's basic pagination is the perfect match for this. If a users requests page _x_ with _y_ results per page, that translates to `$query->setStart(($x - 1) * $y)->setRows($y)->setSort('...')` in Solarium.

If you use infinite scroll to load results sequentially, you could use a cursorMark. Instead of telling Solr "I want this many results starting at that position", you tell it "this is where I got to, give me the next part" by using the nextCursorMark that gets returned with your result. Your first request would need `$query->setRows($y)->setSort('...')->setCursorMark('*')` and subsequent requests would need `$query->setRows($y)->setSort('...')->setCursorMark($result->getNextCursorMark())`. You could as easily do this with basic pagination. The most important difference is that you must add the uniqueKey field to your sort for cursorMark.

PrefetchIterator's use cases are more likely to involve background processes and cronjobs. It comes in handy when you want to process all results for a query (can be `*:*` for your entire index) because it deals with repeating the query every _y_ rows for you. This plugin predates cursorMark and uses basic pagination by default. It does support cursorMark now, but will never add it automatically because it can't determine if you have added the uniqueKey field to your sort. It's straightforward set-and-forget though, `$query->setCursorMark('*')` is all it takes. Whether it's really necessary depends on your index size, but I've never noticed an adverse effect when using it on a smaller index. There's an integration test that asserts prefetching without and with cursorMark yields the same results in the same order for otherwise identical queries.
https://github.com/solariumphp/solarium/blob/2b4639e979657cb26cc74559dba9274e48c73148/tests/Integration/AbstractTechproductsTest.php#L1533

> it will iterate everything and get the results back or while we iterate it sends the request?

While you iterate, it will send a new request for a set of results every time you've "used up" the results that were fetched in the last request.

> if I pull 1M records all of them going to be saved in the "documents" variable or only the last fetch?

Every fetch throws away the documents from the previous fetch. You'll never have more than 1 fetch's worth of documents in memory.

> What's going on when I do count($prefetch)? It's iterate all the result or just return the numFound?

It just returns numFound. If no results have been fetched yet, it will fetch the first set only.

> It means that I will be able to process all the 1M records without save them to a variable but it will save the last fetch?

It will save the last fetch, but you can't really access them anymore once you've iterated over them. If you really want them cleared from memory, you can invoke `$prefetch->setPrefetch($y)` with any value and it will reset the saved results.

> The Prefetch plugin not adding it? I was sure that it's adding it automatically, I've used the sort but not the setCursormark - it mean it was not active right?

It wasn't active. Prefetch doesn't add a cursorMark unless you specifically tell it to.

> After adding $query->setCursormark('*'); I didn't not get duplicates but there was a lot of data missing.

It shouldn't be doing that. There was a small bug in `PrefetchIterator` that might affect you if you loop with `for` or `while`. In that case `$prefetch->rewind()` before starting the loop will fix it. With `foreach`, it should function flawlessly.

Does your index change rapidly? Updates that add or remove documents or change what order they're sorted in can result in documents "jumping" pages (and thus showing up multiple times or being skipped) between fetches for basic paging. With cursorMark this is limited to index modifications that change how matched documents will be sorted. You can avoid this by sorting on the uniqueKey field only. Can you test this on a copy of your index that doesn't receive any updates at all?

If you use date math relative to `NOW`, it can also mess with results because the value of `NOW` will be recalculated with every request. It's best to determine a timestamp in your code and set it with `$query->setNow($timestamp)` to have it remain consistent throughout prefetch.

> Can I use my own pagination instead of Prefetch? I will add and update the setCursormark, is it possible?

Sure you can if you use standard select and `$query->setRows($y)->setSort('...')->setCursorMark('*')` followed by `$query->setRows($y)->setSort('...')->setCursorMark($result->getNextCursorMark())`. The whole point of PrefetchIterator is that you shouldn't have to though.

**Comment by wickedOne** [comment]
i think this comment should be converted into documentation

**Comment by thomascorthals** [comment]
> Last question is the ParallelExecution can work with the PrefetchIterator plugin?

ParallelExecution takes multiple queries (instances of a class implementing `Solarium\Component\QueryInterface`) and plugins aren't such classes. So no, you can't pass multiple PrefetchIterators to ParallelExecution. I'm not even sure how that would be supposed to work. The results for all queries only become available after all queries have finished. To do any meaningful parallel execution with prefetch, you would have to let them all fetch _all_ documents and keep everything in memory. Otherwise they'd just fetch whenever you iterate beyond what was already fetched and you can only do that on one iterator at a time. Unless you're multi-threading from the CLI but then you already have a way to execute them in parallel.

The other way around doesn't make much sense either. Parallel execution of queries inside a single PrefetchIterator is pointless because the next query is only executed when you've used up the fetched documents. If you were to execute multiple fetches in parallel, you'd again end up storing a lot more documents in memory and you'd still only be able to run through them sequentially. With a cursorMark, you wouldn't even have the nextCursorMark yet to start a parallel query with.

What exactly is it that you were hoping to achieve with this combination?

**Comment by thomascorthals** [comment]
> After adding $query->setCursormark('*'); I didn't not get duplicates but there was a lot of data missing.

I've discovered a bug in PrefetchIterator that can cause duplicates if you `break` out of a `foreach` at an arbitrary position and then `foreach` over the same iterator again. It also happens when manually calling `rewind()` at an arbitrary position if you use `for`or `while`. See #907 for the full details. This bug will be fixed in the next Solarium release. In the mean time, you can work around it by calling `$prefetch->setPrefetch($y)` with any value (can be the same as it was) before the second `foreach` or that `rewind()`.
