### ISSUE TITLE
Coding style adjustments?

### ISSUE THREAD

**Issue by dmaicher** [solariumphp/solarium#747]
While working on the first PR I noticed a few things:
- void return types not consistent throughout the codebase
    - https://github.com/solariumphp/solarium/blob/master/tests/QueryType/Select/Query/FilterQueryTest.php#L17
    - https://github.com/solariumphp/solarium/blob/master/tests/Core/Query/LocalParameters/LocalParametersTest.php#L74
- lots of unnecessary phpdoc for stuff that is expressed with type-hints already
    - https://github.com/solariumphp/solarium/blob/master/src/Core/Query/LocalParameters/LocalParameters.php#L36
- some `@throws` phpdocs that seem mostly useless:
    - https://github.com/solariumphp/solarium/blob/master/tests/Core/Query/LocalParameters/LocalParametersTest.php#L22

Are you open for adjusting this? Mostly this can be automated anyway :blush: Whats the opinion of the maintainers?

**Comment by wickedOne** [comment]
personally, on the phpdoc and @throws annotations, i prefer having them.

not only does it the ease of code review, but typehinting for example
```php
 // ...
 *  @return \Solarium\Component\Result\Facet\Pivot\Pivot[]
 // ...
```
instead of having
```php
// ...
public function getPivots(): array
// ...
```
has quite some benefits when using for instance phpstorm as your ide.

i'm not sure what you mean with a useless throw annotation. if an exception is thrown in a method i'd prefer to have that annotated. if you mean that annotations and typehinting is rather useless in unit tests, i could agree with you as there's no ide benefit, but on the other hand it serves the purpose of consistency in the library so i'm somewhat on the fence on that one

**Comment by dmaicher** [comment]
The phpdoc you mention above makes perfect sense for me :+1: I was talking more about 

```php
@return string
```

or similar cases that bring zero additional value as the information is in typehints like 

```php
function foo(): string 
```

already. So I mean to remove duplicated phpdocs only.

Regarding the exceptions: yes mainly I find them useless in the tests :smile: No one will ever call phpunit test methods and care if it throws something or not. Its adds a lot of visual depth and is just more code to read. But maybe thats just my opinion.

**Comment by wickedOne** [comment]
that would result in some methods with annotations and some without, which in my opion makes the codebase messier than anything else (again referring to code review and reading code  in general).

nevertheless, codestyles are there to get rid of opinions :-)
> Solarium follows the Symfony2 code standards: http://symfony.com/doc/current/contributing/code/standards.html

according to the [contributing.md](https://github.com/solariumphp/solarium/blob/master/CONTRIBUTING.md) while the symfony coding standard still states

> Add PHPDoc blocks for all classes, methods, and functions (though you may be asked to remove PHPDoc that do not add value);

https://symfony.com/doc/current/contributing/code/standards.html#documentation

while that not explicitly states there have to be param, return and throws annotations, it would be the most logic default content of any phpdoc block

**Comment by dmaicher** [comment]
> that would result in some methods with annotations and some without

yes indeed :blush: that is also the case in the Symfony codebase. PHPdocs are only there if they add any additional value.

Check this class for example:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1965

**Comment by wickedOne** [comment]
yes:
> while the symfony coding standard **_still_** states
symfony coding standard isn't necessarily the same as the symfony codebase ...

> PHPdocs are only there if they add any additional value.

that's subjective... :-) 
as said, to me the additional value would be readability, ease of code review and aesthetics so there's my additional value. 

anyway i don't think this is the place to discuss the value / thruthiness of a code standard.

**Comment by mkalkbrenner** [comment]
Solarium already has its history. Have a look at the code base of the early 3.x branch to get an impression how it looked like when I joined the project ;-)
But that's normal for a project that started 10 years ago on a different PHP version and without RFCs.
So a lot of things evolved and hopefully improved. But we're far from beeing consistent regarding code standards or - even worse - patterns across the code base. But that's OK and we could change and improve things step by step.
So the bottom line is, yes, we're open for changes and we proved that multiple times in this projects history :-)
But we should have a consensus about what should be done.
Regarding PHPdocs, I prefer the redundancy instead of just adding docs when they add value.
That looks more consistent and eases the task for the style checker.
But again, if something else is more common today, I'm open to accept changes.
Should we start a poll?

**Comment by wickedOne** [comment]
same here; i'm all for enforcing a code style to have a consistent code base and increase the ease of reviewing and remove the need for explaining why code needs to be like it should be.

if we decide to enforce the symfony code style, it should be an fairly easy task by requiring https://github.com/djoos/Symfony-coding-standard to our dev requirements and probably make some changes for the travis configuration.

in my opinion the thing we need to avoid is discussions whether or not you agree with certain aspects of the code style (at least in this repository). 

as for the phpdocs, the symfony code style unfortunately adds an opinion to it (which pretty much defeats the purpose of a code style). for now it still states the requirement of phpdocs, but seeing where their code base is going style wise, i wouldn't be surprised if they remove that part alltogether (and adding PSR-12 to it for that matter).

so yeah, i'd opt to get to a consensus regarding code style and stick with it regardless of it's evolvement. a poll might indeed be a good way to get everyone's opinion on that

**Comment by thomascorthals** [comment]
On the PHPDoc, I'm in "team consistency" with @wickedOne.

Something I noticed regarding exceptions:

Most of the time, we throw exceptions that implement `\Solarium\Exception\ExceptionInterface`. On a few occasions, we throw a bare `\InvalidArgumentException` or `\RuntimeException`. The two classes that throw a `\RuntimeException` in one method, throw a `\Solarium\Exception\RuntimeException` in another. If there's a valid reason for using the bare exceptions, a short comment can clear up the confusion. If not, we should always throw the same kind of exceptions.

**Comment by wickedOne** [comment]
agreed, it would be an improvement if we can agree that each exception thrown in this library would extend the solarium ``ExceptionInterface`` or we might to decide to create our own extend of the ``\RuntimeException`` and build a solarium specific exception tree from there.

this way it's easier for libraries that rely on solarium to distinguish our exceptions from the ones which might be thrown by other libraries downstream.

**Comment by thomascorthals** [comment]
We can't build a Solarium specific tree all under `\RuntimeException`. `InvalidArgumentException` is a `\LogicException`. Extending the bare exceptions and implementing the interface seems fine to me. You can handle them the same way if you don't care whether or not they were thrown by Solarium, or you can distinguish based on the interface.

Perhaps `HttpException` and `StreamException` could extend a Solarium exception instead of a bare exception? At the moment, `\Solarium\Exception\HttpException` _is_ a `\RuntimeException` but _isn't_ a `\Solarium\Exception\RuntimeException`. It would remain a `\RuntimeException` as well by changing the inheritance tree. Is there a specific reason it's like this? Would changing it break anything?

**Comment by wickedOne** [comment]
i personnally cannot think of a scenario which will be break if we move both ``HttpException`` and ``StreamException`` to extend the ``\Solarium\Exception\RuntimeException`` and for consistency i think it's better if we do so

**Comment by thomascorthals** [comment]
Should we add [`@coversNothing`](https://phpunit.readthedocs.io/en/9.0/annotations.html#coversnothing) to our Integration tests?

**Comment by wickedOne** [comment]
yes i'm pro using `` @coversNothing `` as a default for integration tests.

if we run into a situation that a integration test is the only way to test a part of the library (though i cannot think of one atm), we should be ok with leaving out that annotation and accept a comment describing why this can only be covered during integration tests

**Comment by wickedOne** [comment]
any chance we can reach a conclusion on this one?

the code base is becoming a mixture of all things discussed and i personally would prefer we come to a consensus (at least for the ``/src`` directory) and move forward from there.

so how about implementing the [symfony coding standard](https://symfony.com/doc/current/contributing/code/standards.html) for the ``src/`` directory by implementing [these](https://github.com/djoos/Symfony-coding-standard) sniffs and the php-cs-fixer config currently in the repo enforced on new contributions?

i currently have the time to implement this and modify the current code base, so more than happy to do so

**Comment by thomascorthals** [comment]
@wickedOne Sounds good to me! I'm a big fan of consistency.

**Comment by mkalkbrenner** [comment]
@wickedOne do it :-)
