### ISSUE TITLE
schema api

### ISSUE THREAD

**Issue by wickedOne** [solariumphp/solarium#753]
> The file named "managed-schema" in the example configurations may include a note that recommends never hand-editing the file. Before the Schema API existed, such edits were the only way to make changes to the schema, and users may have a strong desire to continue making changes this way.

> The reason that this is discouraged is because hand-edits of the schema may be lost if the Schema API described here is later used to make a change, unless the core or collection is reloaded or Solr is restarted before using the Schema API. If care is taken to always reload or restart after a manual edit, then there is no problem at all with doing those edits.

https://lucene.apache.org/solr/guide/8_4/schema-api.html

this should be a fairly easy implementation by defining a new query type while it offers great flexibility by offering schema modifications programmatically

**Comment by mkalkbrenner** [comment]
Since https://github.com/solariumphp/solarium/releases/tag/5.0.0 we basically support the V2 API.

Using https://github.com/solariumphp/solarium/blob/master/src/QueryType/Server/Api/Query.php you can already use the Schema API (and any other Solr API) kind of "manually".

We should carefully decide if we should really create "classes" as before or  if we should provide an easy to use generic kind of query builder for V2.

**Comment by wickedOne** [comment]
hmmm, very good point indeed...

as said, i've been working on this one briefly last thursday so i think i'll move that code to my api's namespace and build it on top of the solarium v2 query and see what i run into / can come up with in terms of a query builder for easing the management of these modifications.

what do you think?

**Comment by wickedOne** [comment]
closed for now
