### ISSUE TITLE
Add support for ExtractingRequestHandler (PDF, Word, etc.)

### ISSUE THREAD

**Issue by xoob** [solariumphp/solarium#77]
A common use case for Solr is indexing rich document content such as PDF, Word or HTML by using the `ExtractingRequestHandler` and Tika library. Solarium should support extract queries as part of the standard library.

I do have a working Solarium plugin that I would like to integrate upstream. It has been tested and used against Solr 1.4 and aside some minor issues works well.

In order to integrate it, these are the changes I would like to get your feedback on:
- **Add new _extract_ query type**
  - `Solarium_Query_Extract` **new**
  - `Solarium_Client_RequestBuilder_Extract` **new**
  - `Solarium_Client_ResponseParser_Update`
- **Add support for file uploads in requests**
  - Document files are posted to the extract handler in the same way a browser would upload them. The client classes need to support this behaviour.
  - This takes the form of `Request::setFile($path)` or `Request::addFile($path)` if we can support multiple files at once.
  - `Solarium_Client_Request`
  - `Solarium_Client_Adapter`
- **Add support for `multipart/form-data`**
  - If a large number of literal fields is sent with the extract as `GET` fields, Tomcat will go belly-up because the query string limit is reached. This can be avoided by submitting all parameters inside the `POST` body as a `multipart/form-data` payload. Although not documented in the wiki, Solr [supports this request format](http://lucene.472066.n3.nabble.com/form-data-post-to-ExtractingRequestHandler-with-utf-8-characters-not-handled-td3461731.html).
  - This format triggers automatically when a file is added to the request.
  - Should it trigger automatically at a certain number / size of params?
  - `Solarium_Client_Adapter_Http`
  - `Solarium_Client_Adapter_PeclHttp`
  - `Solarium_Client_Adapter_ZendHttp`
- **Docs**
  - Update docs according to new capabilities

Let me know your thoughts on the approach described and I'll start working on the integration. By the way, Solarium is awesome and it's worked fantastically for my project so far!

**Comment by nisha-kajale** [comment]
Hi,
I have installed solarium - 3.4 and SOLR - 5.3.0
I want a facitity to upload pdf and index it using solarium. 
I tried to do this using the code above
<?php

include('library/Configurable.php');
include('library/Client.php');
include('library/client/Adapter.php');
include('library/Client/Adapter/ZendHttp.php');
include('library/Document/ReadOnly.php');
include('library/Document/ReadWrite.php');
include('library/Query.php');
include('library/Query/Extract.php');
include('library/Client/RequestBuilder.php');
include('library/Client/RequestBuilder/Extract.php');
include('library/Client/Request.php');

$client = new Solarium_Client(array(
'adapter' => 'Solarium_Client_Adapter_ZendHttp',
'adapteroptions' => array(
'host' => '192.168.7.4',
'port' => '8983',
),
));

$doc = new Solarium_Document_ReadWrite();

$doc->id = time();
$doc->some = 'more fields';

$extract = new Solarium_Query_Extract();
$extract->addFieldMapping('content', 'text');
$extract->setUprefix('ignore_');
$extract->setDocument($doc);
$extract->setFile('/var/www/solarium/proyek.pdf');

$client->execute($extract);

But in my solarium library folder 
Many of the above files does not exist.

Can you please help me out on this?
Can you give me a solution on how to index rich documents like pdfs using solarium.

Thanks in advance
Nisha

**Comment by basdenooijer** [comment]
It seems like you're using Solarium 2 syntax with a Solarium 3 library. 
Take a look here for a recent example: https://github.com/solariumphp/solarium/blob/master/examples/2.7-extract-query.php

**Comment by nisha-kajale** [comment]
Hi, 
Thanks for your reply so quickly. Can you please elaborate and give me any example where i can see how pdf upload is handled using solarium.

Thanks,
Nisha

**Comment by kostalihas** [comment]
hi every one how i can indexing rich data from a dirctory who contient 5000 files, I try this code: 
$dir = new Folder($dossier);
$files = $dir->find('.*\.*');
foreach ($files as $file) {
    $file = new File($dir->pwd() . DS . $file);

    $update = $client->createUpdate();

    $query = $client->createExtract();
    $query->setFile($file->pwd());
    $query->setCommit(true);
    $query->setOmitHeader(false);

$doc = $query->createDocument();
$doc->id =$file->pwd();
$doc->name = $file->name;
$doc->title = $file->name();
$query->setDocument($doc);

$result = $client->extract($query);
}
but after 10 second i have this error: Solr HTTP error: HTTP request failed, Operation timed out after 5039 milliseconds with 0 out of -1 bytes received

Error: An Internal Error Has Occurred.

**Comment by basdenooijer** [comment]
I could be as simple as raising the timeout, but first of all I would suggest to try a ping query (using the same client instance) to validate your connection settings.

**Comment by kostalihas** [comment]
Tank you for your answer ;my connection setting is fine  because solr index 64 files before this Error, I get from my trace of solr log : 
org.apache.solr.common.SolrException: URLDecoder: Invalid character encoding detected after position 79 of query string / form data (while parsing as UTF-8)

**Comment by kostalihas** [comment]
This is my question in stackoverflow : 
http://stackoverflow.com/questions/34017889/solrexception-urldecoder-invalid-character-encoding-detected-after-position-79

**Comment by kostalihas** [comment]
i fixed by post the right encoding in Headers:
$headers = array('Content-Type:multipart/form-data');
 but he still a smal prb from time out 30sc of wamp server then i can just put 130files to a directory to index untill i index all my files .

I saw Curl is the default adapter for solarium 3 x Iam looking for How to force the connection to explicitly close when it has finished processing, and not be pooled for reuse.

How the server may send a keep-alive timeout (with default Apache install, it is 15 seconds or 100 requests, whichever comes first) - but cURL will just open another connection when that happens.

this is my function index document:


App::import('Vendor','autoload',array('file'=>'solarium/vendor/autoload.php'));

public function indexDocument(){
$config = array(
         "endpoint" => array("localhost" => array("host"=>"127.0.0.1",
         "port"=>"8983", "path"=>"/solr", "core"=>"demo",)
        ) );
       $start = microtime(true);

if($_POST){
            // create a client instance
$client = new Solarium\Client($config);
$dossier=$this->request->data['User']['dossier'];
$dir = new Folder($dossier);
$files = $dir->find('.*\.*');

 $headers = array('Content-Type:multipart/form-data');

foreach ($files as $file) {
    $file = new File($dir->pwd() . DS . $file);

$query = $client->createExtract();
$query->setFile($file->pwd());
$query->setCommit(true);
$query->setOmitHeader(false);

$doc = $query->createDocument();
$doc->id =$file->pwd();
$doc->name = $file->name;
$doc->title = $file->name();

$query->setDocument($doc);

$request = $client->createRequest($query);
$request->addHeaders($headers);

$client->executeRequest($request);
}
    
}

$this->set(compact('start'));
}
