### ISSUE TITLE
Solarium 6: AdapterInterface and ConfigurableInterface

### ISSUE THREAD

**Issue by dmaicher** [solariumphp/solarium#774]
Currently `AdapterInterface` extends `ConfigurableInterface` which is not a good idea imho.

The new `Psr18Adapter` for example does not make use of this at all.

To follow the "interface segregation principle" we should not force all adapters to implement `ConfigurableInterface`.

Remaining questions:
- do we rely anywhere in the code on master that all instances of `AdapterInterface` are also implementing `ConfigurableInterface`?
- as this would be a breaking change in 6.0: do we add deprecations (we discussed it [here](https://github.com/solariumphp/solarium/pull/754#issuecomment-593583513) also) on 5.x?

**Comment by thomascorthals** [comment]
@wickedOne mentioned deprecating the `Configurable` god object in #752.

**Comment by mkalkbrenner** [comment]
I managed to get search_api_solr to work with solarium 5.0 and 5.1. And with the current code base of the upcoming versions 5.2 and 6.0.

It is required to support these solarium versions in parallel because of the fact different solarium versions are used in Drupal 8 and 9.

As I mentioned in previous discussions we distinguish between different timeouts:
- search timeout
- index timeout
- optimize timeout
- finalization timeout

And these timeouts differ for different endpoints using the same adapter.

Finally I found an "easy" way to keep the existing functionality in a way compatible to all solarium 5 and 6 versions:

I set these four values as "options" on the endpoint objects and the adapter. The adapter holds the default values and the endpoints the concrete values that differ from the defaults.

This way I also use the ConfigurableInterface on the Psr18Adapter, too!

I know that the approach is kind of hacked. But other approaches would have caused much more code changes and incompatibilities for other modules that depend on search_api_solr.

I just want to mention this and ask for careful decisions here.

**Comment by dmaicher** [comment]
@mkalkbrenner not sure I understand this point

> This way I also use the ConfigurableInterface on the Psr18Adapter, too!

So did you modify the `Psr18Adapter` so it uses its options?

**Comment by mkalkbrenner** [comment]
Have a look at https://git.drupalcode.org/project/acquia_connector/-/blob/8.x-1.x/acquia_search/src/Plugin/SolrConnector/SearchApiSolrAcquiaConnector.php#L198 as example. this code need to be changed to use the Psr18Adapter.
(And there're other third party Solr service providers/hosters that have their own implementation of search_api_solr's Solr ConnectorInterface.)
These kind of implementation could be easily adapted to the Psr18Adapter. But if the Psr18Adapter looses the ConfigurableInterface, all the timeout logic will be broken.

**Comment by mkalkbrenner** [comment]
So I consider the "Configurable Service" to be present on the Psr18Adapter as a conenience feature for third parties that have to port their implementations, even if solarium itself doesn't require it.

To give you some numbers:
There're more than 10,000 active installations of the acquia_connector in combination with search_api_solr manged by individuals or agencies that might run into trouble if their timeout settings will have no effect anymore by surprise.

**Comment by mkalkbrenner** [comment]
We offered this "data container" based on the ConfigurableInterface throughout all solarium classes since a long time. And yes, it could have been misused. But on the other hand it doesn't really hurt us from the library's perspective.

**Comment by dmaicher** [comment]
@mkalkbrenner 

> But if the Psr18Adapter looses the ConfigurableInterface, all the timeout logic will be broken.

> [...] that might run into trouble if their timeout settings will have no effect anymore by surprise.

I still don't get what you mean here. The `Psr18Adapter` **does not support any options at all**. Whatever you set - it's useless. There is no timeout handling via options.

That's why I think it should not be an instance of `ConfigurableInterface` because its just not configurable via options at all :blush: 

If code needs to configure adapters it should probably check if thats supported by the adapter in Solarium 6?

Like

```php
if ($adapter instanceof ConfigurableInterface) {
    $adapter->setOptions(...);
}

**Comment by dmaicher** [comment]
@mkalkbrenner or you want to avoid exactly those if conditions? So we just make keep all adapters configurable even if its in fact not used at all?

**Comment by mkalkbrenner** [comment]
The adapter (and the endpoints) "transport" options, they're not aware of:
```php
$endpoint->getOption(self::OPTIMIZE_TIMEOUT);
```
I don't consider this to be best practice, but it is very handy to carry the information across different modules and layer of the application.

But I reviewed the code again and in fact we don't need that "feature" on the Psr18Adpater anymore, just on Endpoints since I encapsulated all the "magic" in this function:
```php
  public function useTimeout(string $timeout = self::QUERY_TIMEOUT, ?Endpoint $endpoint = NULL) {
    $this->connect();

    if (!$endpoint) {
      $endpoint = $this->solr->getEndpoint();
    }
    $adpater = $this->solr->getAdapter();
    if ($adpater instanceof TimeoutAwareInterface && ($seconds = $endpoint->getOption($timeout))) {
      $adpater->setTimeout($seconds);
    }
    else {
      $this->getLogger()->warning('The function SolrConnectorPluginBase::useTimeout() has no affect because you use a HTTP adapter that is not implementing TimeoutAwareInterface. You need to adjust your SolrConnector accordingly.');
    }
  }
```

So finally I agree and you can go ahead to let the AdapterInterface no longer extend  ConfigurableInterface. But we should keep the ConfigurableInterface on the Endpoint.
