### ISSUE TITLE
Solarium Config generates wrong solr endpoint uri

### ISSUE THREAD

**Issue by Pin0** [solariumphp/solarium#852]
Solarium version 6.0.1
Php version 7.4

My (old) solr 4 endpoint is something like this: http://hostname:8180/ciss4/corename/select 
As one can see there is no /solr/ anywhere. However the code always adds /solr so the uri ends up:

http://hostname:8180/ciss4/solr/corename/select

How do I get rid of that /solr?

Solarium config:
```
$config = array(
    'endpoint' => array(
        'localhost' => array(
            'scheme' => 'http',
            'host' => 'hostname',
            'port' => 8180,
            'path' => '/ciss4',
            'core' => 'corename',
        )
    ),
);
```

I looked at the code and especially in src/Core/Client/Endpoint.php functions getV2BaseUri, getV1BaseUri, getBaseUri as used in AdapterHelper::buildUri but all add the /solr.

I'm not entirely sure this is a bug or a config mistake on my side, but I'm open to any workaround/solution?

**Comment by thomascorthals** [comment]
As discussed in #787 the hardcoded `/solr` is correct for Solr versions supporting the v2 API. Solarium dropped support for Solr versions < 7 and thus generates correct URIs for all supported versions.

The easiest course of action, I think, would be extending the cURL adapter. Override `createHandle` with a method that calls the parent and then replaces the path of the URI for the handle before returning it. If you can't get it to work, I will be able to look into it at a later time when I'm on a computer instead of my phone.

If at all possible, you can also consider upgrading your Solr to a supported (both in the Solr and Solarium sense) version.

**Comment by Pin0** [comment]
Thanks for the quick reply! Your solution seems like a good option. Will try that out myself! 
Otherwise we'll look into updating our solr instance.

Thanks

**Comment by thomascorthals** [comment]
Since [Solarium 6.2.1](https://github.com/solariumphp/solarium/releases/tag/6.2.1), this can be done without workarounds by adding a `context` to the endpoint configuration. It will default to `solr` if omitted.

```php
$config = [
    'endpoint' => [
        'localhost' => [
            'scheme' => 'http',
            'host' => 'hostname',
            'port' => 8180,
            'path' => '/',
            'context' => 'ciss4',
            'core' => 'corename',
        ]
    ]
];
```
