### ISSUE TITLE
Configure endpoint for proxied Solr

### ISSUE THREAD

**Issue by thomascorthals** [solariumphp/solarium#853]
We keep getting issues about accessing Solr on other paths than `/solr` (#787, #815, #852, #938).

I was going to provide an example and doc note of the solution I came up with in #852 for accessing legacy Solrs "at your own risk": extend the cURL adapter and change the path on the returned handle. When trying to pinpoint the Solr version that had the path hardcoded (or maybe it's always been like that), I stumbled upon this optimisation in Solr 6.5.0:
```markdown
* SOLR-9584: Support Solr being proxied with another endpoint than default /solr, by using relative links
  in AdminUI javascripts (Yun Jie Zhou via janhoy)
```

This seems like a legitimate reason for having the endpoint configurable. What is the best way to support this?

1. Include my "hack" in the docs as the solution for proxied Solrs. Not very user-friendly if it's more than a mere courtesy for legacy installations.
2. Make it configurable on `Endpoint`. Must still default to `/solr` as most users won't have to bother with it.
3. Make it possible via the `CustomizeRequest` plugin. It is a customisation on the request of sorts after all.
4. Write a dedicated `ProxiedEndpoint` plugin.

I haven't found any mentions of proxying `/api`. I guess that would also be possible?

**Comment by mkalkbrenner** [comment]
I did some more research:
https://lucene.apache.org/solr/guide/6_6/parameter-reference.html#solrcloud-instance-parameters
https://lucene.apache.org/solr/guide/8_6/parameter-reference.html#solrcloud-instance-parameters

At least for Solr Cloud the "context" could be changed via `hostContext`.

Maybe we should reintroduce the configuration option but name it `context` instead of `path`.

**Comment by wickedOne** [comment]
option 2 sounds best to me and indeed ``context`` seems a more appropriate name
