### ISSUE TITLE
Missing functionality for nested documents associated via a field "comment" .

### ISSUE THREAD

**Issue by davchs** [solariumphp/solarium#870]
**Solarium version(s) affected**: 6.0.1
**Solr version**:8.5.2

**Description**  
Depending on the Solr Documentation [Indexing Nested Child Documents](https://lucene.apache.org/solr/guide/8_6/indexing-nested-documents.html#schema-configuration)  there are two ways to create a nested document but solarium only handle one. 

> It illustrates two styles of adding child documents: the first is associated via a field "comment" (preferred), and the second is done in the classic way now referred to as an "anonymous" or "unlabelled" child document.

Solarium would create a xml like this :
```
<add>
   <doc>
      <field></field>
      <field></field>
      <doc>
      </doc>
      <doc>
      </doc>
   </doc>
</add>
```
this is correct for the second solution 
But solarium doesn't handle the solution "associated via a field "comment" (preferred)" where you would need a structure like this: 
```
<add>
   <doc>
      <field></field>
      <field></field>
      <field>
          <doc>
          </doc>
      </field>
      <field>
           <doc>
           </doc>
      </field>
   </doc>
</add>
```

I'm currently working in a project where I ran into problems with this. In my project i patched the [RequestBuilder](https://github.com/davchs/solarium/commit/6230b4c3e3bbcbcad27625a8172297e80dd63709) to handle it that way. But this would then only handle nested documents associated via a field "comment". I try to find another possible Solution how Solarium could handle both. need tbd

**Comment by thomascorthals** [comment]
It just so happens that I added an integration test for nested documents last month using the preferred style.

https://github.com/solariumphp/solarium/blob/4bdd5aa674641a0751ba7a5846c5b9e31f5c70c9/tests/Integration/AbstractTechproductsTest.php#L958-L996

Can you try and modify this code to work with your data? The test passes against Solr 7 and 8, but maybe I'm not testing (everything) what I'm supposed to be testing.

**Comment by davchs** [comment]
The `$data` in your Snippet would lead to the following XML in Solarium (anonymous children) :
```
<add>
<doc>
    <field name="id">solarium-parent</field>
    <field name="name">Solarium Nested Document Parent</field>
    <field name="cat">solarium-nested-document</field>
    <field name="cat">parent</field>
    <doc>
        <field name="id">solarium-child-1</field>
        <field name="name">Solarium Nested Document Child 1</field>
        <field name="cat">solarium-nested-document</field>
        <field name="cat">child</field>
        <doc>
            <field name="id">solarium-grandchild-1</field>
            <field name="name">Solarium Nested Document Grandchild 1</field>
            <field name="cat">solarium-nested-document</field>
            <field name="cat">grandchild</field>
            <field name="price">1.1</field>
        </doc>
        <field name="price">1</field>
    </doc>
    <doc>
        <field name="id">solarium-child-2</field>
        <field name="name">Solarium Nested Document Child 2</field>
        <field name="cat">solarium-nested-document</field>
        <field name="cat">child</field>
        <doc>
            <field name="id">solarium-grandchild-2</field>
            <field name="name">Solarium Nested Document Grandchild 2</field>
            <field name="cat">solarium-nested-document</field>
            <field name="cat">grandchild</field>
            <field name="price">2.2</field>
        </doc>
        <field name="price">2</field>
    </doc>
</doc>
</add>
```
The XML for the preferred way with your `$data` would look like this: 
```
<add>
    <doc>
        <field name="id">solarium-parent</field>
        <field name="name">Solarium Nested Document Parent</field>
        <field name="cat">solarium-nested-document</field>
        <field name="cat">parent</field>
        <field name="children">
            <doc>
                <field name="id">solarium-child-1</field>
                <field name="name">Solarium Nested Document Child 1</field>
                <field name="cat">solarium-nested-document</field>
                <field name="cat">child</field>
                <field name="grandchildren">
                    <doc>
                        <field name="id">solarium-grandchild-1</field>
                        <field name="name">Solarium Nested Document Grandchild 1</field>
                        <field name="cat">solarium-nested-document</field>
                        <field name="cat">grandchild</field>
                        <field name="price">1.1</field>
                    </doc>
                </field>
                <field name="price">1</field>
            </doc>
            <doc>
                <field name="id">solarium-child-2</field>
                <field name="name">Solarium Nested Document Child 2</field>
                <field name="cat">solarium-nested-document</field>
                <field name="cat">child</field>
                <field name="grandchildren">
                    <doc>
                        <field name="id">solarium-grandchild-2</field>
                        <field name="name">Solarium Nested Document Grandchild 2</field>
                        <field name="cat">solarium-nested-document</field>
                        <field name="cat">grandchild</field>
                        <field name="price">2.2</field>
                    </doc>
                </field>
                <field name="price">2</field>
            </doc>
        </field>
    </doc>
</add>
```
This would lead to a different document structure in Solr and other fields set automatically (l`_nest_path_`,`_nest_parent_`).

**Comment by thomascorthals** [comment]
> I'm not sure if I got you right. You want me to fix the Tests for my Solution ?? (Im already working on that in my free time)

I just meant if you could check that your data could be indexed correctly if you plugged it in `$data` in that test, assuming that the test worked correctly to begin with.

One of these days (also working on it in my free time) I was planning on expanding the test coverage to include anonymous children, which is apparently what I've actually been testing all along. I can update the integration test if you open a PR for your solution. I don't think it'll make the current test fail.

**Comment by davchs** [comment]
Sorry I don't get it. There is nothing wrong whit my data it will be indexed in the correct way solarium would index it by now. 
But solarium only have functionality to handle anonymous nested documents. 

My changes then only would have functionality to handle nested documents associated via a field "comment".  
First I think tests would break, and I need to fix the tests for nested documents associated via a field "comment" before I do a PR.
Second we or the solarium team (IDK) need to decide/discuss which way they want to support.  
The preferred or the anonymous. I think to support both would lead to different problems. Or at least I didn't found a good solution for it by now.

**Comment by thomascorthals** [comment]
There is nothing wrong with your data, there is something wrong with my integration test. That's what I was trying to assess with my first question. 🙂

Don't worry about tests failing when you open the PR. It's a starting point and we'll be happy to give feedback and work from there to sort it out! Part of the confusion on my part with the integration test stems from the fact that we don't have a `_nest_path_` field defined in our schema. That will need to be addressed if we want to fully test nested documents (pinging @mkalkbrenner for this).


I think we can support both labelled and anonymous. According to the [JSON examples in the ref guide](https://lucene.apache.org/solr/guide/8_6/indexing-nested-documents.html#json-examples), it's perfectly safe to assume anonymous children if the field key is `_childDocuments_` and labelled children otherwise. The key for labelled children should of course not be hardcoded. (The examples in the ref guide up until Solr 8.6 are confusing on this point. This has been fixed in [SOLR-14383](https://issues.apache.org/jira/browse/SOLR-14383) for 8.7/9.)

**Comment by davchs** [comment]
Oh, thanks for pointing out the `_childDocuments_` field key. Will Refactor my changes in the eve and start a PR.

**Comment by mkalkbrenner** [comment]
I'm commenting here instead of within the PR as we have more context here.

Obviously the tests need to be "fixed" now as part of the PR.

According to the PR the suggestion is to switch to the "preferred" way and not to support both. Is that correct?
Is that a breaking change for existing indexes?
Currently we only have unit tests. I think an integration test makes sense to really index, query and delete nested documents.

**Comment by thomascorthals** [comment]
We have an integration test for nested documents.

https://github.com/solariumphp/solarium/blob/4bdd5aa674641a0751ba7a5846c5b9e31f5c70c9/tests/Integration/AbstractTechproductsTest.php#L956

I wrote it under the assumption that I was testing labelled children. As it turns out, it has been testing anonymous children all along. I didn't test the nesting to the full extent because that wasn't possible without a `_nest_path_` field in the schema. That's why I believed the integration wouldn't fail with these changes, and it does look like the current failures in the PR are only from unit tests. The integration test is obviously incomplete. I was meaning to expand it (atomic updates, separate test for anonymous children) and will do that after the PR is merged.

I'm inclined to say we need to support both ways if Solr supports both ways and there is a functional difference. If it doesn't matter from a query standpoint, using `_childDocuments_` could be treated the same as any label when indexing. But I'm obviously not entirely well-versed in the intricacies of nested documents.

**Comment by mkalkbrenner** [comment]
> We have an integration test for nested documents.
Shame on me, you should switch to master before searching the code ;-)

If there're no differences in the index regarding the entire CRUD circle, we should not support both ways via solarium's API, just the "preferred" one.

If people still have old assets that rely on the old structure they probably didn't use our API but sent plain XML.

But to be honest I didn't use nested documents in the past and I'm looking forward to see the revised documentation in Solr 8.7.

**Comment by davchs** [comment]
@mkalkbrenner 
We changed the Code, now all tests passes. 
Imho. the only difference is how to build the XML for the "preferred"-way. 
We use this new feature in a Project and didn't run in to any problems, everything works as expected. 
And it supports both ways so if one want to use the anonymous way it's possible as I mentioned in the pull request, by using the `_childDocuments_` key. (Also mentioned in the Solr documentation.)
```
 $update = $client->createUpdate();
        $doc1 = $update->createDocument();
        $doc1->id = uniqueid();
        $doc1->type = 'parent';
        $doc1->title = 'I am parent';
        $doc1->_childDocuments_ = [
            [
                'id' => uniqueid(),
                'type' => 'child',
                'title' => 'I am child 1',
            ],
            [
                'id' => uniqueid(),
                'type' => 'child',
                'title' => 'I am child 2',
            ],
        ];
```
