### ISSUE TITLE
Difference in how tags are added to geofilt and terms

### ISSUE THREAD

**Issue by ejunker** [solariumphp/solarium#946]
**Solarium version(s) affected**: 6.1.4
**Solr version**: 8.5.2

**Description**  
I noticed a difference with how tags are added to `geofilt` and `terms`. With 6.1.3 it has `{!tag=zip}` and with 6.1.4 it does not but it added it as a parameter.

6.1.3
```php
[
     "omitHeader" => "true",
     "wt" => "json",
     "json.nl" => "flat",
     "q" => "*:*",
     "start" => 0,
     "rows" => 10,
     "fl" => "*,score",
     "fq" => "{!tag=zip}{!geofilt pt=45,93 sfield=geo d=123}",
]
```

6.1.4
```php
[
     "omitHeader" => "true",
     "wt" => "json",
     "json.nl" => "flat",
     "q" => "*:*",
     "start" => 0,
     "rows" => 10,
     "fl" => "*,score",
     "fq" => "{!geofilt pt=45,93 sfield=geo d=123 tag=zip}",
]  
```

And there also also differences for `terms`

6.1.3
```
{!tag=memberID}{!terms f=memberID}
```

6.1.4
```
{!terms f=memberID tag=memberID}
```

**How to reproduce**  

Here is some sample code:

```php
$client = app(\Solarium\Client::class);
$query = $client->createSelect();
$geoQuery = $query->getHelper()->geofilt('geo', 45, 93, 123);
$query->createFilterQuery('zip')->setQuery($geoQuery)->addTag('zip');
$query->getRequestBuilder()->build($query)->getParams();
```

I am not an expert in Solr so I am not sure if this alternate syntax is also valid or if this is a bug.

**Comment by thomascorthals** [comment]
This was a bug up until Solarium 6.1.3. The `{!tag=zip}` part is a [Local Parameter](https://solr.apache.org/guide/8_9/local-parameters-in-queries.html) and according to the ref guide:
> You may specify only one local parameters prefix per argument.

This was fixed in Solarium 6.1.4. The current behaviour with all parameters merged in a single local parameters prefix is the only valid syntax.

Don't hesitate to report any issues you should encounter with this.
