### ISSUE TITLE
frange function ,How should I use it?

### ISSUE THREAD

**Issue by htmax** [solariumphp/solarium#961]
**Solarium version(s) affected**: 8
**Solr version**:8

**Description**  
such as {!frange l=2 }query($q)
Excuse me,frange function ,How should I use it?
I want to except the data whose score is lower than xx
Thanks

**Comment by wickedOne** [comment]
currently the ``frange`` local parameter isn't supported by this library and adding optional parameters to local parameters would probably take a bit time for us to implement.

to work around this you could exclude the scores with your query if it's an actual field in your solr schema or you can use the [analytics component](https://solr.apache.org/guide/8_11/analytics.html) which is supported by this library, to make sure your result set excludes results lower than xx

**Comment by htmax** [comment]
![image](https://user-images.githubusercontent.com/20351240/143673127-10343b86-42fb-4141-b575-59bc7e100505.png)
frange function is solr official function

**Comment by wickedOne** [comment]
yes i'm aware that it's a feature from solr, but this library has no affiliation with solr or the apache foundation. supporting solr's features is done by several people primarily in their leisure time and thus no guarantees solr's features are supported by solarium the moment they are released.

our current local parameter implemetation only supports `{!foo=bar,baz}` notation so one with optional parameters requires some re-work of the current implementation.

try one of the two alternatives i provided if you're using this library, otherwise you have to have some patience in order for us to implement this feature

**Comment by thomascorthals** [comment]
As a workaround, you can include the literal local parameter block in the query that you're setting.

```php
$select->setQuery('{!frange l=2}query($q)');
```

It's even possible to use a helper function to build the param block for you.

```php
$select->setQuery(
    $select->getHelper()->qparser(
        'frange',
        [
            'l' => 2,
        ]
    ).'query($q)'
);

```

Since Solarium 6.1.4, this literal param block will get combined correctly with other local parameters that you might set.

**Comment by thomascorthals** [comment]
@htmax I'm closing this as I assume the workaround works for you. Don't hesitate to get back to us if you have any further questions.
