### ISSUE TITLE
Random test failures with github actions

### ISSUE THREAD

**Issue by mkalkbrenner** [solariumphp/solarium#980]
I re-ran the latest tests multiple times. Every time some tests succeed while others fail. But which PHP and Solr combination succeeds and which one fails is random:
https://github.com/solariumphp/solarium/runs/5123480787

Every time I re-run the tests others succeed and others fail.

**Comment by mkalkbrenner** [comment]
The failing tests are always integration tests, sometimes curl, sometime PSR18, ...
It looks like Solr runs into a random state, is not available or some data is not removed sucessfully between the tests.

@thomascorthals are you able to re-produce a fail locally?

**Comment by thomascorthals** [comment]
I pushed the latest `master` to my fork and [all tests completed successfully](https://github.com/thomascorthals/solarium/actions/runs/1819028888).

My local workflows are not really comparable. I'm running them on Windows with `nektos/act` and that has a few limitations. I can't run the full matrix because only one Solr can listen on 8983 at the same time. Running just one combination of PHP/Solr/cloud is usually sufficient. Another limitation is that I can't run PHP 8 this way.

I did run every combination of PHP 7.3 and 7.4 with Solr 7 and 8 in server and cloud mode and they all passed. I also ran the unit tests outside the workflow against a local Solr in PHP 8.0, that passes too.
